server.port=${PORT:8080}
server.error.include-message=always
server.forward-headers-strategy=framework

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/incident_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.thymeleaf.cache=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

app.upload.dir=${UPLOAD_DIR:uploads/evidence}
app.encryption.key=${ENCRYPTION_KEY:TanzaniaCyberSecurityKey2024!!!}

server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true

logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.com.tz.forensics=INFO

# ===== Email (Gmail SMTP - BURE) =====
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.admin.email=${ADMIN_EMAIL:}
